################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lib/marsyas/ADRess.cpp \
../lib/marsyas/ADRessSpectrum.cpp \
../lib/marsyas/ADRessStereoSpectrum.cpp \
../lib/marsyas/ADSR.cpp \
../lib/marsyas/AMDF.cpp \
../lib/marsyas/ANN_node.cpp \
../lib/marsyas/AbsMax.cpp \
../lib/marsyas/AbsSoundFileSink.cpp \
../lib/marsyas/AbsSoundFileSource.cpp \
../lib/marsyas/AbsSoundFileSource2.cpp \
../lib/marsyas/AccentFilterBank.cpp \
../lib/marsyas/Accumulator.cpp \
../lib/marsyas/AimBoxes.cpp \
../lib/marsyas/AimGammatone.cpp \
../lib/marsyas/AimHCL.cpp \
../lib/marsyas/AimHCL2.cpp \
../lib/marsyas/AimLocalMax.cpp \
../lib/marsyas/AimPZFC.cpp \
../lib/marsyas/AimPZFC2.cpp \
../lib/marsyas/AimSAI.cpp \
../lib/marsyas/AimSSI.cpp \
../lib/marsyas/AimVQ.cpp \
../lib/marsyas/Annotator.cpp \
../lib/marsyas/ArffFileSink.cpp \
../lib/marsyas/AuFileSink.cpp \
../lib/marsyas/AuFileSource.cpp \
../lib/marsyas/AubioYin.cpp \
../lib/marsyas/AudioSink.cpp \
../lib/marsyas/AudioSinkBlocking.cpp \
../lib/marsyas/AudioSource.cpp \
../lib/marsyas/AutoCorrelation.cpp \
../lib/marsyas/AutoCorrelationFFT.cpp \
../lib/marsyas/AveragingPattern.cpp \
../lib/marsyas/BICchangeDetector.cpp \
../lib/marsyas/BaseAudioSink.cpp \
../lib/marsyas/BeatAgent.cpp \
../lib/marsyas/BeatHistoFeatures.cpp \
../lib/marsyas/BeatHistogram.cpp \
../lib/marsyas/BeatHistogramFromPeaks.cpp \
../lib/marsyas/BeatPhase.cpp \
../lib/marsyas/BeatReferee.cpp \
../lib/marsyas/BeatTimesSink.cpp \
../lib/marsyas/Biquad.cpp \
../lib/marsyas/CARFAC.cpp \
../lib/marsyas/CARFAC_coeffs.cpp \
../lib/marsyas/Cartesian2Polar.cpp \
../lib/marsyas/Cascade.cpp \
../lib/marsyas/Centroid.cpp \
../lib/marsyas/Chroma.cpp \
../lib/marsyas/ChromaScale.cpp \
../lib/marsyas/ClassOutputSink.cpp \
../lib/marsyas/ClassificationReport.cpp \
../lib/marsyas/Clip.cpp \
../lib/marsyas/Collection.cpp \
../lib/marsyas/CollectionFileSource.cpp \
../lib/marsyas/Color.cpp \
../lib/marsyas/Combinator.cpp \
../lib/marsyas/CommandLineOptions.cpp \
../lib/marsyas/Communicator.cpp \
../lib/marsyas/CompExp.cpp \
../lib/marsyas/Compressor.cpp \
../lib/marsyas/Confidence.cpp \
../lib/marsyas/ConstQFiltering.cpp \
../lib/marsyas/Conversions.cpp \
../lib/marsyas/CrossCorrelation.cpp \
../lib/marsyas/CsvFileSource.cpp \
../lib/marsyas/DCSource.cpp \
../lib/marsyas/DTW.cpp \
../lib/marsyas/DTWWD.cpp \
../lib/marsyas/Daub4.cpp \
../lib/marsyas/DeInterleaveSizecontrol.cpp \
../lib/marsyas/Deinterleave.cpp \
../lib/marsyas/Delay.cpp \
../lib/marsyas/DelaySamples.cpp \
../lib/marsyas/Delta.cpp \
../lib/marsyas/DeltaFirstOrderRegression.cpp \
../lib/marsyas/Differentiator.cpp \
../lib/marsyas/DownSampler.cpp \
../lib/marsyas/ERB.cpp \
../lib/marsyas/EnhADRess.cpp \
../lib/marsyas/EnhADRessStereoSpectrum.cpp \
../lib/marsyas/Envelope.cpp \
../lib/marsyas/Esitar.cpp \
../lib/marsyas/EvEvent.cpp \
../lib/marsyas/EvExpr.cpp \
../lib/marsyas/EvGetUpd.cpp \
../lib/marsyas/EvValUpd.cpp \
../lib/marsyas/ExCommon.cpp \
../lib/marsyas/ExNode.cpp \
../lib/marsyas/ExParser.cpp \
../lib/marsyas/ExScanner.cpp \
../lib/marsyas/ExSymTbl.cpp \
../lib/marsyas/ExVal.cpp \
../lib/marsyas/Expr.cpp \
../lib/marsyas/F0Analysis.cpp \
../lib/marsyas/FM.cpp \
../lib/marsyas/FMeasure.cpp \
../lib/marsyas/FanOutIn.cpp \
../lib/marsyas/Fanin.cpp \
../lib/marsyas/Fanout.cpp \
../lib/marsyas/FileName.cpp \
../lib/marsyas/Filter.cpp \
../lib/marsyas/FlowCutSource.cpp \
../lib/marsyas/FlowThru.cpp \
../lib/marsyas/Flux.cpp \
../lib/marsyas/FullWaveRectifier.cpp \
../lib/marsyas/GMMClassifier.cpp \
../lib/marsyas/GStreamerSource.cpp \
../lib/marsyas/Gain.cpp \
../lib/marsyas/GaussianClassifier.cpp \
../lib/marsyas/HWPS.cpp \
../lib/marsyas/HalfWaveRectifier.cpp \
../lib/marsyas/HarmonicEnhancer.cpp \
../lib/marsyas/HarmonicStrength.cpp \
../lib/marsyas/InductionGT.cpp \
../lib/marsyas/Inject.cpp \
../lib/marsyas/InvSpectrum.cpp \
../lib/marsyas/KNNClassifier.cpp \
../lib/marsyas/Krumhansl_key_finder.cpp \
../lib/marsyas/Kurtosis.cpp \
../lib/marsyas/LPC.cpp \
../lib/marsyas/LPCC.cpp \
../lib/marsyas/LSP.cpp \
../lib/marsyas/Limiter.cpp \
../lib/marsyas/LyonPassiveEar.cpp \
../lib/marsyas/MATLABengine.cpp \
../lib/marsyas/MFCC.cpp \
../lib/marsyas/MP3FileSink.cpp \
../lib/marsyas/MP3FileSource.cpp \
../lib/marsyas/MarControl.cpp \
../lib/marsyas/MarControlManager.cpp \
../lib/marsyas/MarControlValue.cpp \
../lib/marsyas/MarFileSink.cpp \
../lib/marsyas/MarSystem.cpp \
../lib/marsyas/MarSystemManager.cpp \
../lib/marsyas/MarSystemTemplateAdvanced.cpp \
../lib/marsyas/MarSystemTemplateBasic.cpp \
../lib/marsyas/MarSystemTemplateMedium.cpp \
../lib/marsyas/MatchBassModel.cpp \
../lib/marsyas/MathPower.cpp \
../lib/marsyas/MaxArgMax.cpp \
../lib/marsyas/MaxMin.cpp \
../lib/marsyas/McAulayQuatieri.cpp \
../lib/marsyas/Mean.cpp \
../lib/marsyas/MeanAbsoluteDeviation.cpp \
../lib/marsyas/MeddisHairCell.cpp \
../lib/marsyas/Median.cpp \
../lib/marsyas/MedianFilter.cpp \
../lib/marsyas/Memory.cpp \
../lib/marsyas/MemorySource.cpp \
../lib/marsyas/Metric.cpp \
../lib/marsyas/Metric2.cpp \
../lib/marsyas/MidiFileSynthSource.cpp \
../lib/marsyas/MidiInput.cpp \
../lib/marsyas/MidiOutput.cpp \
../lib/marsyas/MinArgMin.cpp \
../lib/marsyas/MixToMono.cpp \
../lib/marsyas/Mono2Stereo.cpp \
../lib/marsyas/MrsLog.cpp \
../lib/marsyas/Negative.cpp \
../lib/marsyas/NoiseGate.cpp \
../lib/marsyas/NoiseSource.cpp \
../lib/marsyas/Norm.cpp \
../lib/marsyas/NormCut.cpp \
../lib/marsyas/NormMatrix.cpp \
../lib/marsyas/NormMaxMin.cpp \
../lib/marsyas/Normalize.cpp \
../lib/marsyas/NormalizeAbs.cpp \
../lib/marsyas/NumericLib.cpp \
../lib/marsyas/OggFileSource.cpp \
../lib/marsyas/OnePole.cpp \
../lib/marsyas/OneRClassifier.cpp \
../lib/marsyas/OnsetTimes.cpp \
../lib/marsyas/OrcaSnip.cpp \
../lib/marsyas/OverlapAdd.cpp \
../lib/marsyas/PCA.cpp \
../lib/marsyas/PWMSource.cpp \
../lib/marsyas/Panorama.cpp \
../lib/marsyas/Parallel.cpp \
../lib/marsyas/ParallelMatrixWeight.cpp \
../lib/marsyas/PatchMatrix.cpp \
../lib/marsyas/PeUtilities.cpp \
../lib/marsyas/Peak2Rms.cpp \
../lib/marsyas/PeakClusterSelect.cpp \
../lib/marsyas/PeakConvert.cpp \
../lib/marsyas/PeakConvert2.cpp \
../lib/marsyas/PeakDistanceHorizontality.cpp \
../lib/marsyas/PeakEnhancer.cpp \
../lib/marsyas/PeakFeatureSelect.cpp \
../lib/marsyas/PeakInObservation.cpp \
../lib/marsyas/PeakLabeler.cpp \
../lib/marsyas/PeakMask.cpp \
../lib/marsyas/PeakPeriods2BPM.cpp \
../lib/marsyas/PeakRatio.cpp \
../lib/marsyas/PeakResidual.cpp \
../lib/marsyas/PeakSynthFFT.cpp \
../lib/marsyas/PeakSynthOsc.cpp \
../lib/marsyas/PeakSynthOscBank.cpp \
../lib/marsyas/PeakViewMerge.cpp \
../lib/marsyas/PeakViewSink.cpp \
../lib/marsyas/PeakViewSource.cpp \
../lib/marsyas/Peaker.cpp \
../lib/marsyas/PeakerAdaptive.cpp \
../lib/marsyas/PeakerOnset.cpp \
../lib/marsyas/PhaseLock.cpp \
../lib/marsyas/PhiSEMFilter.cpp \
../lib/marsyas/PhiSEMSource.cpp \
../lib/marsyas/Pitch2Chroma.cpp \
../lib/marsyas/PitchDiff.cpp \
../lib/marsyas/PlotSink.cpp \
../lib/marsyas/Plucked.cpp \
../lib/marsyas/Polar2Cartesian.cpp \
../lib/marsyas/Power.cpp \
../lib/marsyas/PowerSpectrum.cpp \
../lib/marsyas/PowerToAverageRatio.cpp \
../lib/marsyas/Product.cpp \
../lib/marsyas/PvConvert.cpp \
../lib/marsyas/PvConvolve.cpp \
../lib/marsyas/PvFold.cpp \
../lib/marsyas/PvMultiResolution.cpp \
../lib/marsyas/PvOscBank.cpp \
../lib/marsyas/PvOverlapadd.cpp \
../lib/marsyas/PvUnconvert.cpp \
../lib/marsyas/QGMMModel.cpp \
../lib/marsyas/RBF.cpp \
../lib/marsyas/RadioDrumInput.cpp \
../lib/marsyas/RawFileSource.cpp \
../lib/marsyas/RealvecSink.cpp \
../lib/marsyas/RealvecSource.cpp \
../lib/marsyas/Reassign.cpp \
../lib/marsyas/Reciprocal.cpp \
../lib/marsyas/RemoveObservations.cpp \
../lib/marsyas/Repeat.cpp \
../lib/marsyas/Resample.cpp \
../lib/marsyas/ResampleBezier.cpp \
../lib/marsyas/ResampleLinear.cpp \
../lib/marsyas/ResampleNearestNeighbour.cpp \
../lib/marsyas/ResampleSinc.cpp \
../lib/marsyas/Reverse.cpp \
../lib/marsyas/Rms.cpp \
../lib/marsyas/Rolloff.cpp \
../lib/marsyas/RunningAutocorrelation.cpp \
../lib/marsyas/RunningStatistics.cpp \
../lib/marsyas/SCF.cpp \
../lib/marsyas/SFM.cpp \
../lib/marsyas/SMO.cpp \
../lib/marsyas/SNR.cpp \
../lib/marsyas/SOM.cpp \
../lib/marsyas/SVMClassifier.cpp \
../lib/marsyas/Scheduler.cpp \
../lib/marsyas/Selector.cpp \
../lib/marsyas/SelfSimilarityMatrix.cpp \
../lib/marsyas/SeneffEar.cpp \
../lib/marsyas/Series.cpp \
../lib/marsyas/ShiftInput.cpp \
../lib/marsyas/ShiftOutput.cpp \
../lib/marsyas/Shifter.cpp \
../lib/marsyas/Shredder.cpp \
../lib/marsyas/Signum.cpp \
../lib/marsyas/SilenceRemove.cpp \
../lib/marsyas/SimilarityMatrix.cpp \
../lib/marsyas/SimulMaskingFft.cpp \
../lib/marsyas/SineSource.cpp \
../lib/marsyas/Skewness.cpp \
../lib/marsyas/SliceDelta.cpp \
../lib/marsyas/SliceShuffle.cpp \
../lib/marsyas/SoundFileSink.cpp \
../lib/marsyas/SoundFileSource.cpp \
../lib/marsyas/SoundFileSource2.cpp \
../lib/marsyas/SoundFileSourceHopper.cpp \
../lib/marsyas/SpectralFlatnessAllBands.cpp \
../lib/marsyas/SpectralSNR.cpp \
../lib/marsyas/SpectralTransformations.cpp \
../lib/marsyas/Spectrum.cpp \
../lib/marsyas/Spectrum2ACMChroma.cpp \
../lib/marsyas/Spectrum2Chroma.cpp \
../lib/marsyas/Spectrum2Mel.cpp \
../lib/marsyas/Square.cpp \
../lib/marsyas/StandardDeviation.cpp \
../lib/marsyas/StereoSpectrum.cpp \
../lib/marsyas/StereoSpectrumFeatures.cpp \
../lib/marsyas/StereoSpectrumSources.cpp \
../lib/marsyas/Stk.cpp \
../lib/marsyas/StretchLinear.cpp \
../lib/marsyas/Subtract.cpp \
../lib/marsyas/SubtractMean.cpp \
../lib/marsyas/Sum.cpp \
../lib/marsyas/Talk.cpp \
../lib/marsyas/TempoHypotheses.cpp \
../lib/marsyas/Thread.cpp \
../lib/marsyas/TimeFreqPeakConnectivity.cpp \
../lib/marsyas/TimeLine.cpp \
../lib/marsyas/TimeStretch.cpp \
../lib/marsyas/TimelineLabeler.cpp \
../lib/marsyas/TmControlValue.cpp \
../lib/marsyas/TmParam.cpp \
../lib/marsyas/TmRealTime.cpp \
../lib/marsyas/TmSampleCount.cpp \
../lib/marsyas/TmTime.cpp \
../lib/marsyas/TmTimer.cpp \
../lib/marsyas/TmTimerManager.cpp \
../lib/marsyas/TmVirtualTime.cpp \
../lib/marsyas/Transcriber.cpp \
../lib/marsyas/TranscriberExtract.cpp \
../lib/marsyas/Transposer.cpp \
../lib/marsyas/Unfold.cpp \
../lib/marsyas/UpdatingBassModel.cpp \
../lib/marsyas/Vibrato.cpp \
../lib/marsyas/ViconFileSource.cpp \
../lib/marsyas/WHaSp.cpp \
../lib/marsyas/WavFileSink.cpp \
../lib/marsyas/WavFileSource.cpp \
../lib/marsyas/WavFileSource2.cpp \
../lib/marsyas/WaveletBands.cpp \
../lib/marsyas/WaveletPyramid.cpp \
../lib/marsyas/WaveletStep.cpp \
../lib/marsyas/WekaData.cpp \
../lib/marsyas/WekaSink.cpp \
../lib/marsyas/WekaSource.cpp \
../lib/marsyas/Windowing.cpp \
../lib/marsyas/Yin.cpp \
../lib/marsyas/ZeroCrossings.cpp \
../lib/marsyas/ZeroRClassifier.cpp \
../lib/marsyas/basis.cpp \
../lib/marsyas/fft.cpp \
../lib/marsyas/gst-decode.cpp \
../lib/marsyas/lu.cpp \
../lib/marsyas/marohtml.cpp \
../lib/marsyas/marojson.cpp \
../lib/marsyas/marostring.cpp \
../lib/marsyas/marosvg.cpp \
../lib/marsyas/maroxml.cpp \
../lib/marsyas/peakView.cpp \
../lib/marsyas/realvec.cpp \
../lib/marsyas/statistics.cpp \
../lib/marsyas/vmblock.cpp 

OBJS += \
./lib/marsyas/ADRess.o \
./lib/marsyas/ADRessSpectrum.o \
./lib/marsyas/ADRessStereoSpectrum.o \
./lib/marsyas/ADSR.o \
./lib/marsyas/AMDF.o \
./lib/marsyas/ANN_node.o \
./lib/marsyas/AbsMax.o \
./lib/marsyas/AbsSoundFileSink.o \
./lib/marsyas/AbsSoundFileSource.o \
./lib/marsyas/AbsSoundFileSource2.o \
./lib/marsyas/AccentFilterBank.o \
./lib/marsyas/Accumulator.o \
./lib/marsyas/AimBoxes.o \
./lib/marsyas/AimGammatone.o \
./lib/marsyas/AimHCL.o \
./lib/marsyas/AimHCL2.o \
./lib/marsyas/AimLocalMax.o \
./lib/marsyas/AimPZFC.o \
./lib/marsyas/AimPZFC2.o \
./lib/marsyas/AimSAI.o \
./lib/marsyas/AimSSI.o \
./lib/marsyas/AimVQ.o \
./lib/marsyas/Annotator.o \
./lib/marsyas/ArffFileSink.o \
./lib/marsyas/AuFileSink.o \
./lib/marsyas/AuFileSource.o \
./lib/marsyas/AubioYin.o \
./lib/marsyas/AudioSink.o \
./lib/marsyas/AudioSinkBlocking.o \
./lib/marsyas/AudioSource.o \
./lib/marsyas/AutoCorrelation.o \
./lib/marsyas/AutoCorrelationFFT.o \
./lib/marsyas/AveragingPattern.o \
./lib/marsyas/BICchangeDetector.o \
./lib/marsyas/BaseAudioSink.o \
./lib/marsyas/BeatAgent.o \
./lib/marsyas/BeatHistoFeatures.o \
./lib/marsyas/BeatHistogram.o \
./lib/marsyas/BeatHistogramFromPeaks.o \
./lib/marsyas/BeatPhase.o \
./lib/marsyas/BeatReferee.o \
./lib/marsyas/BeatTimesSink.o \
./lib/marsyas/Biquad.o \
./lib/marsyas/CARFAC.o \
./lib/marsyas/CARFAC_coeffs.o \
./lib/marsyas/Cartesian2Polar.o \
./lib/marsyas/Cascade.o \
./lib/marsyas/Centroid.o \
./lib/marsyas/Chroma.o \
./lib/marsyas/ChromaScale.o \
./lib/marsyas/ClassOutputSink.o \
./lib/marsyas/ClassificationReport.o \
./lib/marsyas/Clip.o \
./lib/marsyas/Collection.o \
./lib/marsyas/CollectionFileSource.o \
./lib/marsyas/Color.o \
./lib/marsyas/Combinator.o \
./lib/marsyas/CommandLineOptions.o \
./lib/marsyas/Communicator.o \
./lib/marsyas/CompExp.o \
./lib/marsyas/Compressor.o \
./lib/marsyas/Confidence.o \
./lib/marsyas/ConstQFiltering.o \
./lib/marsyas/Conversions.o \
./lib/marsyas/CrossCorrelation.o \
./lib/marsyas/CsvFileSource.o \
./lib/marsyas/DCSource.o \
./lib/marsyas/DTW.o \
./lib/marsyas/DTWWD.o \
./lib/marsyas/Daub4.o \
./lib/marsyas/DeInterleaveSizecontrol.o \
./lib/marsyas/Deinterleave.o \
./lib/marsyas/Delay.o \
./lib/marsyas/DelaySamples.o \
./lib/marsyas/Delta.o \
./lib/marsyas/DeltaFirstOrderRegression.o \
./lib/marsyas/Differentiator.o \
./lib/marsyas/DownSampler.o \
./lib/marsyas/ERB.o \
./lib/marsyas/EnhADRess.o \
./lib/marsyas/EnhADRessStereoSpectrum.o \
./lib/marsyas/Envelope.o \
./lib/marsyas/Esitar.o \
./lib/marsyas/EvEvent.o \
./lib/marsyas/EvExpr.o \
./lib/marsyas/EvGetUpd.o \
./lib/marsyas/EvValUpd.o \
./lib/marsyas/ExCommon.o \
./lib/marsyas/ExNode.o \
./lib/marsyas/ExParser.o \
./lib/marsyas/ExScanner.o \
./lib/marsyas/ExSymTbl.o \
./lib/marsyas/ExVal.o \
./lib/marsyas/Expr.o \
./lib/marsyas/F0Analysis.o \
./lib/marsyas/FM.o \
./lib/marsyas/FMeasure.o \
./lib/marsyas/FanOutIn.o \
./lib/marsyas/Fanin.o \
./lib/marsyas/Fanout.o \
./lib/marsyas/FileName.o \
./lib/marsyas/Filter.o \
./lib/marsyas/FlowCutSource.o \
./lib/marsyas/FlowThru.o \
./lib/marsyas/Flux.o \
./lib/marsyas/FullWaveRectifier.o \
./lib/marsyas/GMMClassifier.o \
./lib/marsyas/GStreamerSource.o \
./lib/marsyas/Gain.o \
./lib/marsyas/GaussianClassifier.o \
./lib/marsyas/HWPS.o \
./lib/marsyas/HalfWaveRectifier.o \
./lib/marsyas/HarmonicEnhancer.o \
./lib/marsyas/HarmonicStrength.o \
./lib/marsyas/InductionGT.o \
./lib/marsyas/Inject.o \
./lib/marsyas/InvSpectrum.o \
./lib/marsyas/KNNClassifier.o \
./lib/marsyas/Krumhansl_key_finder.o \
./lib/marsyas/Kurtosis.o \
./lib/marsyas/LPC.o \
./lib/marsyas/LPCC.o \
./lib/marsyas/LSP.o \
./lib/marsyas/Limiter.o \
./lib/marsyas/LyonPassiveEar.o \
./lib/marsyas/MATLABengine.o \
./lib/marsyas/MFCC.o \
./lib/marsyas/MP3FileSink.o \
./lib/marsyas/MP3FileSource.o \
./lib/marsyas/MarControl.o \
./lib/marsyas/MarControlManager.o \
./lib/marsyas/MarControlValue.o \
./lib/marsyas/MarFileSink.o \
./lib/marsyas/MarSystem.o \
./lib/marsyas/MarSystemManager.o \
./lib/marsyas/MarSystemTemplateAdvanced.o \
./lib/marsyas/MarSystemTemplateBasic.o \
./lib/marsyas/MarSystemTemplateMedium.o \
./lib/marsyas/MatchBassModel.o \
./lib/marsyas/MathPower.o \
./lib/marsyas/MaxArgMax.o \
./lib/marsyas/MaxMin.o \
./lib/marsyas/McAulayQuatieri.o \
./lib/marsyas/Mean.o \
./lib/marsyas/MeanAbsoluteDeviation.o \
./lib/marsyas/MeddisHairCell.o \
./lib/marsyas/Median.o \
./lib/marsyas/MedianFilter.o \
./lib/marsyas/Memory.o \
./lib/marsyas/MemorySource.o \
./lib/marsyas/Metric.o \
./lib/marsyas/Metric2.o \
./lib/marsyas/MidiFileSynthSource.o \
./lib/marsyas/MidiInput.o \
./lib/marsyas/MidiOutput.o \
./lib/marsyas/MinArgMin.o \
./lib/marsyas/MixToMono.o \
./lib/marsyas/Mono2Stereo.o \
./lib/marsyas/MrsLog.o \
./lib/marsyas/Negative.o \
./lib/marsyas/NoiseGate.o \
./lib/marsyas/NoiseSource.o \
./lib/marsyas/Norm.o \
./lib/marsyas/NormCut.o \
./lib/marsyas/NormMatrix.o \
./lib/marsyas/NormMaxMin.o \
./lib/marsyas/Normalize.o \
./lib/marsyas/NormalizeAbs.o \
./lib/marsyas/NumericLib.o \
./lib/marsyas/OggFileSource.o \
./lib/marsyas/OnePole.o \
./lib/marsyas/OneRClassifier.o \
./lib/marsyas/OnsetTimes.o \
./lib/marsyas/OrcaSnip.o \
./lib/marsyas/OverlapAdd.o \
./lib/marsyas/PCA.o \
./lib/marsyas/PWMSource.o \
./lib/marsyas/Panorama.o \
./lib/marsyas/Parallel.o \
./lib/marsyas/ParallelMatrixWeight.o \
./lib/marsyas/PatchMatrix.o \
./lib/marsyas/PeUtilities.o \
./lib/marsyas/Peak2Rms.o \
./lib/marsyas/PeakClusterSelect.o \
./lib/marsyas/PeakConvert.o \
./lib/marsyas/PeakConvert2.o \
./lib/marsyas/PeakDistanceHorizontality.o \
./lib/marsyas/PeakEnhancer.o \
./lib/marsyas/PeakFeatureSelect.o \
./lib/marsyas/PeakInObservation.o \
./lib/marsyas/PeakLabeler.o \
./lib/marsyas/PeakMask.o \
./lib/marsyas/PeakPeriods2BPM.o \
./lib/marsyas/PeakRatio.o \
./lib/marsyas/PeakResidual.o \
./lib/marsyas/PeakSynthFFT.o \
./lib/marsyas/PeakSynthOsc.o \
./lib/marsyas/PeakSynthOscBank.o \
./lib/marsyas/PeakViewMerge.o \
./lib/marsyas/PeakViewSink.o \
./lib/marsyas/PeakViewSource.o \
./lib/marsyas/Peaker.o \
./lib/marsyas/PeakerAdaptive.o \
./lib/marsyas/PeakerOnset.o \
./lib/marsyas/PhaseLock.o \
./lib/marsyas/PhiSEMFilter.o \
./lib/marsyas/PhiSEMSource.o \
./lib/marsyas/Pitch2Chroma.o \
./lib/marsyas/PitchDiff.o \
./lib/marsyas/PlotSink.o \
./lib/marsyas/Plucked.o \
./lib/marsyas/Polar2Cartesian.o \
./lib/marsyas/Power.o \
./lib/marsyas/PowerSpectrum.o \
./lib/marsyas/PowerToAverageRatio.o \
./lib/marsyas/Product.o \
./lib/marsyas/PvConvert.o \
./lib/marsyas/PvConvolve.o \
./lib/marsyas/PvFold.o \
./lib/marsyas/PvMultiResolution.o \
./lib/marsyas/PvOscBank.o \
./lib/marsyas/PvOverlapadd.o \
./lib/marsyas/PvUnconvert.o \
./lib/marsyas/QGMMModel.o \
./lib/marsyas/RBF.o \
./lib/marsyas/RadioDrumInput.o \
./lib/marsyas/RawFileSource.o \
./lib/marsyas/RealvecSink.o \
./lib/marsyas/RealvecSource.o \
./lib/marsyas/Reassign.o \
./lib/marsyas/Reciprocal.o \
./lib/marsyas/RemoveObservations.o \
./lib/marsyas/Repeat.o \
./lib/marsyas/Resample.o \
./lib/marsyas/ResampleBezier.o \
./lib/marsyas/ResampleLinear.o \
./lib/marsyas/ResampleNearestNeighbour.o \
./lib/marsyas/ResampleSinc.o \
./lib/marsyas/Reverse.o \
./lib/marsyas/Rms.o \
./lib/marsyas/Rolloff.o \
./lib/marsyas/RunningAutocorrelation.o \
./lib/marsyas/RunningStatistics.o \
./lib/marsyas/SCF.o \
./lib/marsyas/SFM.o \
./lib/marsyas/SMO.o \
./lib/marsyas/SNR.o \
./lib/marsyas/SOM.o \
./lib/marsyas/SVMClassifier.o \
./lib/marsyas/Scheduler.o \
./lib/marsyas/Selector.o \
./lib/marsyas/SelfSimilarityMatrix.o \
./lib/marsyas/SeneffEar.o \
./lib/marsyas/Series.o \
./lib/marsyas/ShiftInput.o \
./lib/marsyas/ShiftOutput.o \
./lib/marsyas/Shifter.o \
./lib/marsyas/Shredder.o \
./lib/marsyas/Signum.o \
./lib/marsyas/SilenceRemove.o \
./lib/marsyas/SimilarityMatrix.o \
./lib/marsyas/SimulMaskingFft.o \
./lib/marsyas/SineSource.o \
./lib/marsyas/Skewness.o \
./lib/marsyas/SliceDelta.o \
./lib/marsyas/SliceShuffle.o \
./lib/marsyas/SoundFileSink.o \
./lib/marsyas/SoundFileSource.o \
./lib/marsyas/SoundFileSource2.o \
./lib/marsyas/SoundFileSourceHopper.o \
./lib/marsyas/SpectralFlatnessAllBands.o \
./lib/marsyas/SpectralSNR.o \
./lib/marsyas/SpectralTransformations.o \
./lib/marsyas/Spectrum.o \
./lib/marsyas/Spectrum2ACMChroma.o \
./lib/marsyas/Spectrum2Chroma.o \
./lib/marsyas/Spectrum2Mel.o \
./lib/marsyas/Square.o \
./lib/marsyas/StandardDeviation.o \
./lib/marsyas/StereoSpectrum.o \
./lib/marsyas/StereoSpectrumFeatures.o \
./lib/marsyas/StereoSpectrumSources.o \
./lib/marsyas/Stk.o \
./lib/marsyas/StretchLinear.o \
./lib/marsyas/Subtract.o \
./lib/marsyas/SubtractMean.o \
./lib/marsyas/Sum.o \
./lib/marsyas/Talk.o \
./lib/marsyas/TempoHypotheses.o \
./lib/marsyas/Thread.o \
./lib/marsyas/TimeFreqPeakConnectivity.o \
./lib/marsyas/TimeLine.o \
./lib/marsyas/TimeStretch.o \
./lib/marsyas/TimelineLabeler.o \
./lib/marsyas/TmControlValue.o \
./lib/marsyas/TmParam.o \
./lib/marsyas/TmRealTime.o \
./lib/marsyas/TmSampleCount.o \
./lib/marsyas/TmTime.o \
./lib/marsyas/TmTimer.o \
./lib/marsyas/TmTimerManager.o \
./lib/marsyas/TmVirtualTime.o \
./lib/marsyas/Transcriber.o \
./lib/marsyas/TranscriberExtract.o \
./lib/marsyas/Transposer.o \
./lib/marsyas/Unfold.o \
./lib/marsyas/UpdatingBassModel.o \
./lib/marsyas/Vibrato.o \
./lib/marsyas/ViconFileSource.o \
./lib/marsyas/WHaSp.o \
./lib/marsyas/WavFileSink.o \
./lib/marsyas/WavFileSource.o \
./lib/marsyas/WavFileSource2.o \
./lib/marsyas/WaveletBands.o \
./lib/marsyas/WaveletPyramid.o \
./lib/marsyas/WaveletStep.o \
./lib/marsyas/WekaData.o \
./lib/marsyas/WekaSink.o \
./lib/marsyas/WekaSource.o \
./lib/marsyas/Windowing.o \
./lib/marsyas/Yin.o \
./lib/marsyas/ZeroCrossings.o \
./lib/marsyas/ZeroRClassifier.o \
./lib/marsyas/basis.o \
./lib/marsyas/fft.o \
./lib/marsyas/gst-decode.o \
./lib/marsyas/lu.o \
./lib/marsyas/marohtml.o \
./lib/marsyas/marojson.o \
./lib/marsyas/marostring.o \
./lib/marsyas/marosvg.o \
./lib/marsyas/maroxml.o \
./lib/marsyas/peakView.o \
./lib/marsyas/realvec.o \
./lib/marsyas/statistics.o \
./lib/marsyas/vmblock.o 

CPP_DEPS += \
./lib/marsyas/ADRess.d \
./lib/marsyas/ADRessSpectrum.d \
./lib/marsyas/ADRessStereoSpectrum.d \
./lib/marsyas/ADSR.d \
./lib/marsyas/AMDF.d \
./lib/marsyas/ANN_node.d \
./lib/marsyas/AbsMax.d \
./lib/marsyas/AbsSoundFileSink.d \
./lib/marsyas/AbsSoundFileSource.d \
./lib/marsyas/AbsSoundFileSource2.d \
./lib/marsyas/AccentFilterBank.d \
./lib/marsyas/Accumulator.d \
./lib/marsyas/AimBoxes.d \
./lib/marsyas/AimGammatone.d \
./lib/marsyas/AimHCL.d \
./lib/marsyas/AimHCL2.d \
./lib/marsyas/AimLocalMax.d \
./lib/marsyas/AimPZFC.d \
./lib/marsyas/AimPZFC2.d \
./lib/marsyas/AimSAI.d \
./lib/marsyas/AimSSI.d \
./lib/marsyas/AimVQ.d \
./lib/marsyas/Annotator.d \
./lib/marsyas/ArffFileSink.d \
./lib/marsyas/AuFileSink.d \
./lib/marsyas/AuFileSource.d \
./lib/marsyas/AubioYin.d \
./lib/marsyas/AudioSink.d \
./lib/marsyas/AudioSinkBlocking.d \
./lib/marsyas/AudioSource.d \
./lib/marsyas/AutoCorrelation.d \
./lib/marsyas/AutoCorrelationFFT.d \
./lib/marsyas/AveragingPattern.d \
./lib/marsyas/BICchangeDetector.d \
./lib/marsyas/BaseAudioSink.d \
./lib/marsyas/BeatAgent.d \
./lib/marsyas/BeatHistoFeatures.d \
./lib/marsyas/BeatHistogram.d \
./lib/marsyas/BeatHistogramFromPeaks.d \
./lib/marsyas/BeatPhase.d \
./lib/marsyas/BeatReferee.d \
./lib/marsyas/BeatTimesSink.d \
./lib/marsyas/Biquad.d \
./lib/marsyas/CARFAC.d \
./lib/marsyas/CARFAC_coeffs.d \
./lib/marsyas/Cartesian2Polar.d \
./lib/marsyas/Cascade.d \
./lib/marsyas/Centroid.d \
./lib/marsyas/Chroma.d \
./lib/marsyas/ChromaScale.d \
./lib/marsyas/ClassOutputSink.d \
./lib/marsyas/ClassificationReport.d \
./lib/marsyas/Clip.d \
./lib/marsyas/Collection.d \
./lib/marsyas/CollectionFileSource.d \
./lib/marsyas/Color.d \
./lib/marsyas/Combinator.d \
./lib/marsyas/CommandLineOptions.d \
./lib/marsyas/Communicator.d \
./lib/marsyas/CompExp.d \
./lib/marsyas/Compressor.d \
./lib/marsyas/Confidence.d \
./lib/marsyas/ConstQFiltering.d \
./lib/marsyas/Conversions.d \
./lib/marsyas/CrossCorrelation.d \
./lib/marsyas/CsvFileSource.d \
./lib/marsyas/DCSource.d \
./lib/marsyas/DTW.d \
./lib/marsyas/DTWWD.d \
./lib/marsyas/Daub4.d \
./lib/marsyas/DeInterleaveSizecontrol.d \
./lib/marsyas/Deinterleave.d \
./lib/marsyas/Delay.d \
./lib/marsyas/DelaySamples.d \
./lib/marsyas/Delta.d \
./lib/marsyas/DeltaFirstOrderRegression.d \
./lib/marsyas/Differentiator.d \
./lib/marsyas/DownSampler.d \
./lib/marsyas/ERB.d \
./lib/marsyas/EnhADRess.d \
./lib/marsyas/EnhADRessStereoSpectrum.d \
./lib/marsyas/Envelope.d \
./lib/marsyas/Esitar.d \
./lib/marsyas/EvEvent.d \
./lib/marsyas/EvExpr.d \
./lib/marsyas/EvGetUpd.d \
./lib/marsyas/EvValUpd.d \
./lib/marsyas/ExCommon.d \
./lib/marsyas/ExNode.d \
./lib/marsyas/ExParser.d \
./lib/marsyas/ExScanner.d \
./lib/marsyas/ExSymTbl.d \
./lib/marsyas/ExVal.d \
./lib/marsyas/Expr.d \
./lib/marsyas/F0Analysis.d \
./lib/marsyas/FM.d \
./lib/marsyas/FMeasure.d \
./lib/marsyas/FanOutIn.d \
./lib/marsyas/Fanin.d \
./lib/marsyas/Fanout.d \
./lib/marsyas/FileName.d \
./lib/marsyas/Filter.d \
./lib/marsyas/FlowCutSource.d \
./lib/marsyas/FlowThru.d \
./lib/marsyas/Flux.d \
./lib/marsyas/FullWaveRectifier.d \
./lib/marsyas/GMMClassifier.d \
./lib/marsyas/GStreamerSource.d \
./lib/marsyas/Gain.d \
./lib/marsyas/GaussianClassifier.d \
./lib/marsyas/HWPS.d \
./lib/marsyas/HalfWaveRectifier.d \
./lib/marsyas/HarmonicEnhancer.d \
./lib/marsyas/HarmonicStrength.d \
./lib/marsyas/InductionGT.d \
./lib/marsyas/Inject.d \
./lib/marsyas/InvSpectrum.d \
./lib/marsyas/KNNClassifier.d \
./lib/marsyas/Krumhansl_key_finder.d \
./lib/marsyas/Kurtosis.d \
./lib/marsyas/LPC.d \
./lib/marsyas/LPCC.d \
./lib/marsyas/LSP.d \
./lib/marsyas/Limiter.d \
./lib/marsyas/LyonPassiveEar.d \
./lib/marsyas/MATLABengine.d \
./lib/marsyas/MFCC.d \
./lib/marsyas/MP3FileSink.d \
./lib/marsyas/MP3FileSource.d \
./lib/marsyas/MarControl.d \
./lib/marsyas/MarControlManager.d \
./lib/marsyas/MarControlValue.d \
./lib/marsyas/MarFileSink.d \
./lib/marsyas/MarSystem.d \
./lib/marsyas/MarSystemManager.d \
./lib/marsyas/MarSystemTemplateAdvanced.d \
./lib/marsyas/MarSystemTemplateBasic.d \
./lib/marsyas/MarSystemTemplateMedium.d \
./lib/marsyas/MatchBassModel.d \
./lib/marsyas/MathPower.d \
./lib/marsyas/MaxArgMax.d \
./lib/marsyas/MaxMin.d \
./lib/marsyas/McAulayQuatieri.d \
./lib/marsyas/Mean.d \
./lib/marsyas/MeanAbsoluteDeviation.d \
./lib/marsyas/MeddisHairCell.d \
./lib/marsyas/Median.d \
./lib/marsyas/MedianFilter.d \
./lib/marsyas/Memory.d \
./lib/marsyas/MemorySource.d \
./lib/marsyas/Metric.d \
./lib/marsyas/Metric2.d \
./lib/marsyas/MidiFileSynthSource.d \
./lib/marsyas/MidiInput.d \
./lib/marsyas/MidiOutput.d \
./lib/marsyas/MinArgMin.d \
./lib/marsyas/MixToMono.d \
./lib/marsyas/Mono2Stereo.d \
./lib/marsyas/MrsLog.d \
./lib/marsyas/Negative.d \
./lib/marsyas/NoiseGate.d \
./lib/marsyas/NoiseSource.d \
./lib/marsyas/Norm.d \
./lib/marsyas/NormCut.d \
./lib/marsyas/NormMatrix.d \
./lib/marsyas/NormMaxMin.d \
./lib/marsyas/Normalize.d \
./lib/marsyas/NormalizeAbs.d \
./lib/marsyas/NumericLib.d \
./lib/marsyas/OggFileSource.d \
./lib/marsyas/OnePole.d \
./lib/marsyas/OneRClassifier.d \
./lib/marsyas/OnsetTimes.d \
./lib/marsyas/OrcaSnip.d \
./lib/marsyas/OverlapAdd.d \
./lib/marsyas/PCA.d \
./lib/marsyas/PWMSource.d \
./lib/marsyas/Panorama.d \
./lib/marsyas/Parallel.d \
./lib/marsyas/ParallelMatrixWeight.d \
./lib/marsyas/PatchMatrix.d \
./lib/marsyas/PeUtilities.d \
./lib/marsyas/Peak2Rms.d \
./lib/marsyas/PeakClusterSelect.d \
./lib/marsyas/PeakConvert.d \
./lib/marsyas/PeakConvert2.d \
./lib/marsyas/PeakDistanceHorizontality.d \
./lib/marsyas/PeakEnhancer.d \
./lib/marsyas/PeakFeatureSelect.d \
./lib/marsyas/PeakInObservation.d \
./lib/marsyas/PeakLabeler.d \
./lib/marsyas/PeakMask.d \
./lib/marsyas/PeakPeriods2BPM.d \
./lib/marsyas/PeakRatio.d \
./lib/marsyas/PeakResidual.d \
./lib/marsyas/PeakSynthFFT.d \
./lib/marsyas/PeakSynthOsc.d \
./lib/marsyas/PeakSynthOscBank.d \
./lib/marsyas/PeakViewMerge.d \
./lib/marsyas/PeakViewSink.d \
./lib/marsyas/PeakViewSource.d \
./lib/marsyas/Peaker.d \
./lib/marsyas/PeakerAdaptive.d \
./lib/marsyas/PeakerOnset.d \
./lib/marsyas/PhaseLock.d \
./lib/marsyas/PhiSEMFilter.d \
./lib/marsyas/PhiSEMSource.d \
./lib/marsyas/Pitch2Chroma.d \
./lib/marsyas/PitchDiff.d \
./lib/marsyas/PlotSink.d \
./lib/marsyas/Plucked.d \
./lib/marsyas/Polar2Cartesian.d \
./lib/marsyas/Power.d \
./lib/marsyas/PowerSpectrum.d \
./lib/marsyas/PowerToAverageRatio.d \
./lib/marsyas/Product.d \
./lib/marsyas/PvConvert.d \
./lib/marsyas/PvConvolve.d \
./lib/marsyas/PvFold.d \
./lib/marsyas/PvMultiResolution.d \
./lib/marsyas/PvOscBank.d \
./lib/marsyas/PvOverlapadd.d \
./lib/marsyas/PvUnconvert.d \
./lib/marsyas/QGMMModel.d \
./lib/marsyas/RBF.d \
./lib/marsyas/RadioDrumInput.d \
./lib/marsyas/RawFileSource.d \
./lib/marsyas/RealvecSink.d \
./lib/marsyas/RealvecSource.d \
./lib/marsyas/Reassign.d \
./lib/marsyas/Reciprocal.d \
./lib/marsyas/RemoveObservations.d \
./lib/marsyas/Repeat.d \
./lib/marsyas/Resample.d \
./lib/marsyas/ResampleBezier.d \
./lib/marsyas/ResampleLinear.d \
./lib/marsyas/ResampleNearestNeighbour.d \
./lib/marsyas/ResampleSinc.d \
./lib/marsyas/Reverse.d \
./lib/marsyas/Rms.d \
./lib/marsyas/Rolloff.d \
./lib/marsyas/RunningAutocorrelation.d \
./lib/marsyas/RunningStatistics.d \
./lib/marsyas/SCF.d \
./lib/marsyas/SFM.d \
./lib/marsyas/SMO.d \
./lib/marsyas/SNR.d \
./lib/marsyas/SOM.d \
./lib/marsyas/SVMClassifier.d \
./lib/marsyas/Scheduler.d \
./lib/marsyas/Selector.d \
./lib/marsyas/SelfSimilarityMatrix.d \
./lib/marsyas/SeneffEar.d \
./lib/marsyas/Series.d \
./lib/marsyas/ShiftInput.d \
./lib/marsyas/ShiftOutput.d \
./lib/marsyas/Shifter.d \
./lib/marsyas/Shredder.d \
./lib/marsyas/Signum.d \
./lib/marsyas/SilenceRemove.d \
./lib/marsyas/SimilarityMatrix.d \
./lib/marsyas/SimulMaskingFft.d \
./lib/marsyas/SineSource.d \
./lib/marsyas/Skewness.d \
./lib/marsyas/SliceDelta.d \
./lib/marsyas/SliceShuffle.d \
./lib/marsyas/SoundFileSink.d \
./lib/marsyas/SoundFileSource.d \
./lib/marsyas/SoundFileSource2.d \
./lib/marsyas/SoundFileSourceHopper.d \
./lib/marsyas/SpectralFlatnessAllBands.d \
./lib/marsyas/SpectralSNR.d \
./lib/marsyas/SpectralTransformations.d \
./lib/marsyas/Spectrum.d \
./lib/marsyas/Spectrum2ACMChroma.d \
./lib/marsyas/Spectrum2Chroma.d \
./lib/marsyas/Spectrum2Mel.d \
./lib/marsyas/Square.d \
./lib/marsyas/StandardDeviation.d \
./lib/marsyas/StereoSpectrum.d \
./lib/marsyas/StereoSpectrumFeatures.d \
./lib/marsyas/StereoSpectrumSources.d \
./lib/marsyas/Stk.d \
./lib/marsyas/StretchLinear.d \
./lib/marsyas/Subtract.d \
./lib/marsyas/SubtractMean.d \
./lib/marsyas/Sum.d \
./lib/marsyas/Talk.d \
./lib/marsyas/TempoHypotheses.d \
./lib/marsyas/Thread.d \
./lib/marsyas/TimeFreqPeakConnectivity.d \
./lib/marsyas/TimeLine.d \
./lib/marsyas/TimeStretch.d \
./lib/marsyas/TimelineLabeler.d \
./lib/marsyas/TmControlValue.d \
./lib/marsyas/TmParam.d \
./lib/marsyas/TmRealTime.d \
./lib/marsyas/TmSampleCount.d \
./lib/marsyas/TmTime.d \
./lib/marsyas/TmTimer.d \
./lib/marsyas/TmTimerManager.d \
./lib/marsyas/TmVirtualTime.d \
./lib/marsyas/Transcriber.d \
./lib/marsyas/TranscriberExtract.d \
./lib/marsyas/Transposer.d \
./lib/marsyas/Unfold.d \
./lib/marsyas/UpdatingBassModel.d \
./lib/marsyas/Vibrato.d \
./lib/marsyas/ViconFileSource.d \
./lib/marsyas/WHaSp.d \
./lib/marsyas/WavFileSink.d \
./lib/marsyas/WavFileSource.d \
./lib/marsyas/WavFileSource2.d \
./lib/marsyas/WaveletBands.d \
./lib/marsyas/WaveletPyramid.d \
./lib/marsyas/WaveletStep.d \
./lib/marsyas/WekaData.d \
./lib/marsyas/WekaSink.d \
./lib/marsyas/WekaSource.d \
./lib/marsyas/Windowing.d \
./lib/marsyas/Yin.d \
./lib/marsyas/ZeroCrossings.d \
./lib/marsyas/ZeroRClassifier.d \
./lib/marsyas/basis.d \
./lib/marsyas/fft.d \
./lib/marsyas/gst-decode.d \
./lib/marsyas/lu.d \
./lib/marsyas/marohtml.d \
./lib/marsyas/marojson.d \
./lib/marsyas/marostring.d \
./lib/marsyas/marosvg.d \
./lib/marsyas/maroxml.d \
./lib/marsyas/peakView.d \
./lib/marsyas/realvec.d \
./lib/marsyas/statistics.d \
./lib/marsyas/vmblock.d 


# Each subdirectory must supply rules for building sources it contributes
lib/marsyas/%.o: ../lib/marsyas/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Users/ellingsenp/Dropbox/Dev/Musicuriousv2/lib/marsyas -I"/Users/ellingsenp/Dropbox/Dev/Musicuriousv2/lib/FMOD Programmers API/api/inc" -I/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/GLUT.framework/Versions/A/Headers -O0 -g3 -Wall -c -fmessage-length=0 -arch i686 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


